name: 24/7 YouTube Live Stream Loop

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Core Environment Boot
        run: |
          sudo apt update
          sudo apt install ffmpeg wget -y

      # exit code 183 চিরতরে দূর করতে পুরোনো সব আবর্জনা ফাইল মেমরি থেকে ক্লিন করা
      - name: Purge and Clean Workspace Memory
        run: |
          rm -rf *
          rm -f stream_video.mp4

      - name: Direct Stream Cash Bypass
        run: |
          # গুগল ড্রাইভের ভাইরাস স্ক্যান বাইপাস করে একদম ফ্রেশ ফাইল ডাউনলোড
          wget --no-check-certificate 'https://google.com' -O stream_video.mp4

      - name: Boot 24/7 RTMP Core Engine
        run: |
          STREAM_KEY="kavx-rgks-8ygz-gmq8-fkxs"
          
          if [ ! -f "stream_video.mp4" ] || [ ! -s "stream_video.mp4" ]; then
              echo "Error: Server memory build failed! Exiting..."
              exit 1
          fi
          
          echo "Server connected successfully! Broadcasting to YouTube..."
          while true
          do
            ffmpeg -re -stream_loop -1 -i stream_video.mp4 \
            -c:v libx264 -preset superfast -b:v 2000k -maxrate 2000k -bufsize 4000k \
            -c:a aac -b:a 128k -ar 44100 \
            -f flv "rtmp://://youtube.com"
            sleep 5
          done

      - name: Chain Trigger Next Session
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://github.com{{ github.repository }}/actions/workflows/live.yml/dispatches \
            -d '{"ref":"main"}'
