name: 24/7 YouTube Live Stream Loop

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

# গিটহাবের নতুন নোটিশ অনুযায়ী সিকিউরিটি বাইপাস এনভায়রনমেন্ট ভেরিয়েবল সেট করা
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install ffmpeg wget python3 python3-pip -y
          # পারমিশন ও আইপি ব্লক এড়াতে লোকাল ডিরেক্টরিতে yt-dlp নামানো
          wget https://github.com
          chmod +x yt-dlp

      - name: Start Unlimited Live Stream
        run: |
          chmod +x app.sh
          timeout 5h 45m ./app.sh || true

      - name: Chain Trigger Next Session
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://github.com{{ github.repository }}/actions/workflows/live.yml/dispatches \
            -d '{"ref":"main"}'
